---
name: Release

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      node-version:
        description: "Node.js version"
        type: number
        required: false
      semantic-release-version:
        description: "Version of semantic-release-action"
        type: string
        required: false
      dry-run:
        description: "Dry run mode"
        type: boolean
        required: false
        default: false
      runs-on:
        description: "Default runner"
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  release:
    name: Release
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get Bot User Metadata
        id: bot-metadata
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          APP_SLUG: ${{ steps.generate-token.outputs.app-slug }}
        run: |
          USER_ID=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)
          if [[ "${{ github.server_url }}" == "https://github.com" ]]; then
            EMAIL_DOMAIN="users.noreply.github.com"
          else
            CLEAN_HOST=$(echo "${{ github.server_url }}" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
            EMAIL_DOMAIN="users.noreply.${CLEAN_HOST}"
          fi

          BOT_NAME="${APP_SLUG}[bot]"
          BOT_EMAIL="${USER_ID}+${APP_SLUG}[bot]@${EMAIL_DOMAIN}"

          echo "Detected Identity: $BOT_NAME <$BOT_EMAIL>"
          echo "bot-name=$BOT_NAME" >> "$GITHUB_OUTPUT"
          echo "bot-email=$BOT_EMAIL" >> "$GITHUB_OUTPUT"
          echo "user-id=$USER_ID" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Set correct Node.js version
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ inputs.node-version || 24 }}

      - name: Install dependencies
        run: |
          npm install \
            semantic-release@25.0.0 \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@12.0.6 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GITHUB_URL: "${{ github.server_url }}"
          GITHUB_API_URL: "${{ github.api_url }}"

          GIT_AUTHOR_NAME: ${{ steps.bot-metadata.outputs.bot-name }}
          GIT_AUTHOR_EMAIL: ${{ steps.bot-metadata.outputs.bot-email }}
          GIT_COMMITTER_NAME: ${{ steps.bot-metadata.outputs.bot-name }}
          GIT_COMMITTER_EMAIL: ${{ steps.bot-metadata.outputs.bot-email }}

        run: npx semantic-release --config .releaserc.json
