---
name: Release

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      node-version:
        description: "Node.js version"
        type: number
        required: false
      semantic-release-version:
        description: "Version of semantic-release-action"
        type: string
        required: false
      dry-run:
        description: "Dry run mode"
        type: boolean
        required: false
        default: false
      runs-on:
        description: "Default runner"
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  release:
    name: Release
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Set correct Node.js version
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ inputs.node-version || 24 }}

      - name: Get App Metadata
        id: app-metadata
        run: |
          BOT_INFO=$(curl -s -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            "${{ github.api_url }}/user")

          BOT_LOGIN=$(echo "$BOT_INFO" | jq -r '.login')
          BOT_ID=$(echo "$BOT_INFO" | jq -r '.id')

          if [[ "${{ github.server_url }}" == "https://github.com" ]]; then
             EMAIL_DOMAIN="users.noreply.github.com"
          else
             EMAIL_DOMAIN=$(echo "${{ github.server_url }}" | sed -e 's|^[^/]*//||')
          fi

          echo "Detected Bot: $BOT_LOGIN (ID: $BOT_ID)"
          echo "bot-name=$BOT_LOGIN" >> $GITHUB_OUTPUT
          echo "bot-id=$BOT_ID" >> $GITHUB_OUTPUT
          echo "domain=$EMAIL_DOMAIN" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          npm install \
            semantic-release@25.0.0 \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@12.0.6 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GITHUB_URL: "${{ github.server_url }}"
          GITHUB_API_URL: "${{ github.api_url }}"

          GIT_AUTHOR_NAME: "${{ steps.app-metadata.outputs.bot-name }}"
          GIT_AUTHOR_EMAIL: "${{ steps.app-metadata.outputs.bot-id }}+${{ steps.app-metadata.outputs.bot-name }}@${{ steps.app-metadata.outputs.domain }}"
          GIT_COMMITTER_NAME: "${{ steps.app-metadata.outputs.bot-name }}"
          GIT_COMMITTER_EMAIL: "${{ steps.app-metadata.outputs.bot-id }}+${{ steps.app-metadata.outputs.bot-name }}@${{ steps.app-metadata.outputs.domain }}"

        run: npx semantic-release --config .releaserc.json
