name: Linters

on:
  pull_request:

jobs:
  action-lint:
    name: action-lint
    uses: ./.github/workflows/linters/action-lint.yml
  yaml-lint:
    name: yaml-lint
    uses: ./.github/workflows/linters/yaml-lint.yml
