name: Linters

on:
  pull_request:

jobs:
  name: Linters
  action-lint:
    name: action-lint
    uses: ./.github/workflows/linter_action.yml
  yaml-lint:
    name: yaml-lint
    uses: ./.github/workflows/linter_yaml.yml
