name: Linters

on:
  pull_request:

jobs:
  action-lint:
    name: action-lint
    uses: ./.github/workflows/linter-action.yml
  yaml-lint:
    name: yaml-lint
    uses: ./.github/workflows/linter-yaml.yml
